//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostVolumeDim
    {
        public HostVolumeDim()
        {
            this.HostHostsHostVolumeFacts = new HashSet<HostHostsHostVolumeFact>();
        }
    
        public int HostVolumeDimKey { get; set; }
        public System.Guid BaseManagedEntityId { get; set; }
        public string ID { get; set; }
        public string MountPoints { get; set; }
        public string Capacity { get; set; }
        public string VolumeLabel { get; set; }
        public string IsClustered { get; set; }
        public string IsClusterSharedVolume { get; set; }
        public string FreeSpace { get; set; }
        public Nullable<bool> IsAvailableForPlacement { get; set; }
        public string Classification { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DWInsertedId { get; set; }
        public Nullable<int> DWUpdatedId { get; set; }
        public Nullable<bool> DWIsDeleted { get; set; }
    
        public virtual ICollection<HostHostsHostVolumeFact> HostHostsHostVolumeFacts { get; set; }
    }
}
