//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostGroupDim
    {
        public HostGroupDim()
        {
            this.HostGroupContainsHostClusterFacts = new HashSet<HostGroupContainsHostClusterFact>();
            this.HostGroupContainsHostGroupFacts = new HashSet<HostGroupContainsHostGroupFact>();
            this.HostGroupContainsHostGroupFacts1 = new HashSet<HostGroupContainsHostGroupFact>();
            this.HostGroupContainsVMHostFacts = new HashSet<HostGroupContainsVMHostFact>();
            this.VirtualMachineBaseUsageMonthlyFacts = new HashSet<VirtualMachineBaseUsageMonthlyFact>();
            this.VirtualMachineBaseUsageHourlyFacts = new HashSet<VirtualMachineBaseUsageHourlyFact>();
            this.VirtualMachineBaseUsageDailyFacts = new HashSet<VirtualMachineBaseUsageDailyFact>();
            this.VirtualMachineBaseUsageDailyFactStagings = new HashSet<VirtualMachineBaseUsageDailyFactStaging>();
            this.VirtualMachineBaseUsageHourlyFactStagings = new HashSet<VirtualMachineBaseUsageHourlyFactStaging>();
        }
    
        public int HostGroupDimKey { get; set; }
        public System.Guid BaseManagedEntityId { get; set; }
        public string VMMId { get; set; }
        public string Path { get; set; }
        public string VMMServer { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DWInsertedId { get; set; }
        public Nullable<int> DWUpdatedId { get; set; }
        public Nullable<bool> DWIsDeleted { get; set; }
    
        public virtual ICollection<HostGroupContainsHostClusterFact> HostGroupContainsHostClusterFacts { get; set; }
        public virtual ICollection<HostGroupContainsHostGroupFact> HostGroupContainsHostGroupFacts { get; set; }
        public virtual ICollection<HostGroupContainsHostGroupFact> HostGroupContainsHostGroupFacts1 { get; set; }
        public virtual ICollection<HostGroupContainsVMHostFact> HostGroupContainsVMHostFacts { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageMonthlyFact> VirtualMachineBaseUsageMonthlyFacts { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageHourlyFact> VirtualMachineBaseUsageHourlyFacts { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageDailyFact> VirtualMachineBaseUsageDailyFacts { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageDailyFactStaging> VirtualMachineBaseUsageDailyFactStagings { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageHourlyFactStaging> VirtualMachineBaseUsageHourlyFactStagings { get; set; }
    }
}
