//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostClusterDim
    {
        public HostClusterDim()
        {
            this.HostClusterContainsVMHostFacts = new HashSet<HostClusterContainsVMHostFact>();
            this.HostGroupContainsHostClusterFacts = new HashSet<HostGroupContainsHostClusterFact>();
        }
    
        public int HostClusterDimKey { get; set; }
        public System.Guid BaseManagedEntityId { get; set; }
        public string VMMId { get; set; }
        public string HostFailureReserve { get; set; }
        public string NumberOfNodes { get; set; }
        public string HostGroup { get; set; }
        public string CommitState { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DWInsertedId { get; set; }
        public Nullable<int> DWUpdatedId { get; set; }
        public Nullable<bool> DWIsDeleted { get; set; }
    
        public virtual ICollection<HostClusterContainsVMHostFact> HostClusterContainsVMHostFacts { get; set; }
        public virtual ICollection<HostGroupContainsHostClusterFact> HostGroupContainsHostClusterFacts { get; set; }
    }
}
