//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HourDim
    {
        public HourDim()
        {
            this.VirtualMachineBaseUsageHourlyFacts = new HashSet<VirtualMachineBaseUsageHourlyFact>();
            this.SubscriptionCapacityHourlyFacts = new HashSet<SubscriptionCapacityHourlyFact>();
            this.SubscriptionCapacityHourlyFactStagings = new HashSet<SubscriptionCapacityHourlyFactStaging>();
            this.VirtualMachineBaseUsageHourlyFactStagings = new HashSet<VirtualMachineBaseUsageHourlyFactStaging>();
            this.VMNetworkGatewayUsageHourlyFacts = new HashSet<VMNetworkGatewayUsageHourlyFact>();
            this.VMNetworkGatewayUsageHourlyFactStagings = new HashSet<VMNetworkGatewayUsageHourlyFactStaging>();
        }
    
        public int HourKey { get; set; }
        public string Time { get; set; }
    
        public virtual ICollection<VirtualMachineBaseUsageHourlyFact> VirtualMachineBaseUsageHourlyFacts { get; set; }
        public virtual ICollection<SubscriptionCapacityHourlyFact> SubscriptionCapacityHourlyFacts { get; set; }
        public virtual ICollection<SubscriptionCapacityHourlyFactStaging> SubscriptionCapacityHourlyFactStagings { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageHourlyFactStaging> VirtualMachineBaseUsageHourlyFactStagings { get; set; }
        public virtual ICollection<VMNetworkGatewayUsageHourlyFact> VMNetworkGatewayUsageHourlyFacts { get; set; }
        public virtual ICollection<VMNetworkGatewayUsageHourlyFactStaging> VMNetworkGatewayUsageHourlyFactStagings { get; set; }
    }
}
