//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsageDatawarehouseDBEntities : DbContext
    {
        public UsageDatawarehouseDBEntities()
            : base("name=UsageDatawarehouseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CloudContainsVirtualMachineFact> CloudContainsVirtualMachineFacts { get; set; }
        public virtual DbSet<CloudDim> CloudDims { get; set; }
        public virtual DbSet<DateDim> DateDims { get; set; }
        public virtual DbSet<HostClusterContainsVMHostFact> HostClusterContainsVMHostFacts { get; set; }
        public virtual DbSet<HostClusterDim> HostClusterDims { get; set; }
        public virtual DbSet<HostContainsVirtualMachineFact> HostContainsVirtualMachineFacts { get; set; }
        public virtual DbSet<HostDim> HostDims { get; set; }
        public virtual DbSet<HostGroupContainsHostClusterFact> HostGroupContainsHostClusterFacts { get; set; }
        public virtual DbSet<HostGroupContainsHostGroupFact> HostGroupContainsHostGroupFacts { get; set; }
        public virtual DbSet<HostGroupContainsVMHostFact> HostGroupContainsVMHostFacts { get; set; }
        public virtual DbSet<HostGroupDim> HostGroupDims { get; set; }
        public virtual DbSet<HostHostsHostVolumeFact> HostHostsHostVolumeFacts { get; set; }
        public virtual DbSet<HostHostsVMHostDiskFact> HostHostsVMHostDiskFacts { get; set; }
        public virtual DbSet<HostVolumeDim> HostVolumeDims { get; set; }
        public virtual DbSet<HourDim> HourDims { get; set; }
        public virtual DbSet<ObjectStore> ObjectStores { get; set; }
        public virtual DbSet<OperatingSystemDim> OperatingSystemDims { get; set; }
        public virtual DbSet<PlanDim> PlanDims { get; set; }
        public virtual DbSet<ProcessorCategoryDim> ProcessorCategoryDims { get; set; }
        public virtual DbSet<SubscriptionCapacityMonthlyFact> SubscriptionCapacityMonthlyFacts { get; set; }
        public virtual DbSet<SubscriptionDim> SubscriptionDims { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TenantDim> TenantDims { get; set; }
        public virtual DbSet<UserRoleContainsQuotaFact> UserRoleContainsQuotaFacts { get; set; }
        public virtual DbSet<UserRoleDim> UserRoleDims { get; set; }
        public virtual DbSet<UserRoleQuotaDim> UserRoleQuotaDims { get; set; }
        public virtual DbSet<UserRoleReferencesCloudFact> UserRoleReferencesCloudFacts { get; set; }
        public virtual DbSet<UserRoleReferencesVMNetworkFact> UserRoleReferencesVMNetworkFacts { get; set; }
        public virtual DbSet<VirtualDiskDim> VirtualDiskDims { get; set; }
        public virtual DbSet<VirtualMachineBaseUsageMonthlyFact> VirtualMachineBaseUsageMonthlyFacts { get; set; }
        public virtual DbSet<VirtualMachineContainsVirtualDiskFact> VirtualMachineContainsVirtualDiskFacts { get; set; }
        public virtual DbSet<VirtualMachineContainsVirtualNicFact> VirtualMachineContainsVirtualNicFacts { get; set; }
        public virtual DbSet<VirtualMachineDim> VirtualMachineDims { get; set; }
        public virtual DbSet<VirtualNicDim> VirtualNicDims { get; set; }
        public virtual DbSet<VMHostDiskDim> VMHostDiskDims { get; set; }
        public virtual DbSet<VMInventoryMonthlyFact> VMInventoryMonthlyFacts { get; set; }
        public virtual DbSet<VMMServerDim> VMMServerDims { get; set; }
        public virtual DbSet<VMNetworkDim> VMNetworkDims { get; set; }
        public virtual DbSet<VMNetworkGatewayDim> VMNetworkGatewayDims { get; set; }
        public virtual DbSet<VMNetworkGatewayUsageMonthlyFact> VMNetworkGatewayUsageMonthlyFacts { get; set; }
        public virtual DbSet<VirtualMachineBaseUsageHourlyFact> VirtualMachineBaseUsageHourlyFacts { get; set; }
        public virtual DbSet<SubscriptionCapacityDailyFact> SubscriptionCapacityDailyFacts { get; set; }
        public virtual DbSet<SubscriptionCapacityDailyFactStaging> SubscriptionCapacityDailyFactStagings { get; set; }
        public virtual DbSet<SubscriptionCapacityHourlyFact> SubscriptionCapacityHourlyFacts { get; set; }
        public virtual DbSet<SubscriptionCapacityHourlyFactStaging> SubscriptionCapacityHourlyFactStagings { get; set; }
        public virtual DbSet<VirtualMachineBaseUsageDailyFact> VirtualMachineBaseUsageDailyFacts { get; set; }
        public virtual DbSet<VirtualMachineBaseUsageDailyFactStaging> VirtualMachineBaseUsageDailyFactStagings { get; set; }
        public virtual DbSet<VirtualMachineBaseUsageHourlyFactStaging> VirtualMachineBaseUsageHourlyFactStagings { get; set; }
        public virtual DbSet<VMNetworkGatewayUsageDailyFact> VMNetworkGatewayUsageDailyFacts { get; set; }
        public virtual DbSet<VMNetworkGatewayUsageDailyFactStaging> VMNetworkGatewayUsageDailyFactStagings { get; set; }
        public virtual DbSet<VMNetworkGatewayUsageHourlyFact> VMNetworkGatewayUsageHourlyFacts { get; set; }
        public virtual DbSet<VMNetworkGatewayUsageHourlyFactStaging> VMNetworkGatewayUsageHourlyFactStagings { get; set; }
    }
}
