//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectStore
    {
        public int ObjectID { get; set; }
        public string ObjectName { get; set; }
        public string ObjectType { get; set; }
        public int ObjectVersionNumber { get; set; }
        public Nullable<int> RetentionPeriodInMinutes { get; set; }
        public Nullable<int> GroomingIntervalInMinutes { get; set; }
        public string ProcessModuleNameLike { get; set; }
        public string Grain { get; set; }
    }
}
