//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingSystemDim
    {
        public OperatingSystemDim()
        {
            this.VMInventoryMonthlyFacts = new HashSet<VMInventoryMonthlyFact>();
        }
    
        public int OperatingSystemDimKey { get; set; }
        public string EditionName { get; set; }
        public string OSName { get; set; }
        public string OSVersion { get; set; }
        public bool OSCounted { get; set; }
    
        public virtual ICollection<VMInventoryMonthlyFact> VMInventoryMonthlyFacts { get; set; }
    }
}
