//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleQuotaDim
    {
        public UserRoleQuotaDim()
        {
            this.UserRoleContainsQuotaFacts = new HashSet<UserRoleContainsQuotaFact>();
        }
    
        public int UserRoleQuotaDimKey { get; set; }
        public System.Guid BaseManagedEntityId { get; set; }
        public string RoleID { get; set; }
        public string CloudId { get; set; }
        public Nullable<bool> UseVMCountDefault { get; set; }
        public Nullable<bool> UseCPUCountDefault { get; set; }
        public Nullable<bool> UseMemoryMBDefault { get; set; }
        public Nullable<bool> UseStorageGBDefault { get; set; }
        public Nullable<bool> UseCustomQuotaCountDefault { get; set; }
        public Nullable<int> VMCount { get; set; }
        public Nullable<int> CPUCount { get; set; }
        public Nullable<int> MemoryMB { get; set; }
        public Nullable<int> StorageGB { get; set; }
        public Nullable<int> CustomQuotaCount { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DWInsertedId { get; set; }
        public Nullable<int> DWUpdatedId { get; set; }
        public Nullable<bool> DWIsDeleted { get; set; }
    
        public virtual ICollection<UserRoleContainsQuotaFact> UserRoleContainsQuotaFacts { get; set; }
    }
}
