//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualMachineDim
    {
        public VirtualMachineDim()
        {
            this.CloudContainsVirtualMachineFacts = new HashSet<CloudContainsVirtualMachineFact>();
            this.HostContainsVirtualMachineFacts = new HashSet<HostContainsVirtualMachineFact>();
            this.VirtualMachineBaseUsageMonthlyFacts = new HashSet<VirtualMachineBaseUsageMonthlyFact>();
            this.VirtualMachineContainsVirtualDiskFacts = new HashSet<VirtualMachineContainsVirtualDiskFact>();
            this.VirtualMachineContainsVirtualNicFacts = new HashSet<VirtualMachineContainsVirtualNicFact>();
            this.VMInventoryMonthlyFacts = new HashSet<VMInventoryMonthlyFact>();
            this.VirtualMachineBaseUsageHourlyFacts = new HashSet<VirtualMachineBaseUsageHourlyFact>();
            this.VirtualMachineBaseUsageDailyFacts = new HashSet<VirtualMachineBaseUsageDailyFact>();
            this.VirtualMachineBaseUsageDailyFactStagings = new HashSet<VirtualMachineBaseUsageDailyFactStaging>();
            this.VirtualMachineBaseUsageHourlyFactStagings = new HashSet<VirtualMachineBaseUsageHourlyFactStaging>();
        }
    
        public int VirtualMachineDimKey { get; set; }
        public System.Guid BaseManagedEntityId { get; set; }
        public string CPUCount { get; set; }
        public string State { get; set; }
        public string CostCenter { get; set; }
        public string TotalSizeOfVirtualDisks { get; set; }
        public Nullable<bool> DynamicMemory { get; set; }
        public string Cloud { get; set; }
        public string Description { get; set; }
        public string VMMId { get; set; }
        public string Owner { get; set; }
        public string VMMServer { get; set; }
        public string CreationDate { get; set; }
        public string NoOfNICs { get; set; }
        public string GuestFQDN { get; set; }
        public string DeploymentLocation { get; set; }
        public string DisplayName { get; set; }
        public string TotalRAM { get; set; }
        public string NoOfVirtualDisks { get; set; }
        public string HostName { get; set; }
        public string VGS { get; set; }
        public string MaxMemoryMB { get; set; }
        public string OwnerUserRole { get; set; }
        public Nullable<int> VirtualProcCount { get; set; }
        public string ServiceTemplateId { get; set; }
        public string OperatingSystem { get; set; }
        public string OperatingSystemVersion { get; set; }
        public Nullable<bool> IsHighlyAvailable { get; set; }
        public Nullable<int> TotalVirtualDiskSizeMBytes { get; set; }
        public Nullable<int> MaxMemoryMBytes { get; set; }
        public Nullable<int> DWInsertedId { get; set; }
        public Nullable<int> DWUpdatedId { get; set; }
        public Nullable<bool> DWIsDeleted { get; set; }
        public int OperatingSystemDimKey { get; set; }
    
        public virtual ICollection<CloudContainsVirtualMachineFact> CloudContainsVirtualMachineFacts { get; set; }
        public virtual ICollection<HostContainsVirtualMachineFact> HostContainsVirtualMachineFacts { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageMonthlyFact> VirtualMachineBaseUsageMonthlyFacts { get; set; }
        public virtual ICollection<VirtualMachineContainsVirtualDiskFact> VirtualMachineContainsVirtualDiskFacts { get; set; }
        public virtual ICollection<VirtualMachineContainsVirtualNicFact> VirtualMachineContainsVirtualNicFacts { get; set; }
        public virtual ICollection<VMInventoryMonthlyFact> VMInventoryMonthlyFacts { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageHourlyFact> VirtualMachineBaseUsageHourlyFacts { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageDailyFact> VirtualMachineBaseUsageDailyFacts { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageDailyFactStaging> VirtualMachineBaseUsageDailyFactStagings { get; set; }
        public virtual ICollection<VirtualMachineBaseUsageHourlyFactStaging> VirtualMachineBaseUsageHourlyFactStagings { get; set; }
    }
}
