//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualMachineBaseUsageDailyFactStaging
    {
        public long VirtualMachineBaseUsageDailyFactKey { get; set; }
        public int CloudDimKey { get; set; }
        public int HostGroupDimKey { get; set; }
        public int HostDimKey { get; set; }
        public int VirtualMachineDimKey { get; set; }
        public int UserRoleDimKey { get; set; }
        public int VMMServerDimKey { get; set; }
        public int TenantDimKey { get; set; }
        public int PlanDimKey { get; set; }
        public int SubscriptionDimKey { get; set; }
        public int DateKey { get; set; }
        public Nullable<double> StaticMemoryAllocated { get; set; }
        public Nullable<double> MemoryUsage { get; set; }
        public Nullable<double> CoreAllocated { get; set; }
        public Nullable<double> CoreConsumption { get; set; }
        public Nullable<double> RAMConsumption { get; set; }
        public Nullable<double> TotalVMRunTime { get; set; }
        public Nullable<double> DiskIOPS { get; set; }
        public Nullable<double> DiskSpaceAllocated { get; set; }
        public Nullable<double> DiskSpaceUsage { get; set; }
        public int DWInsertedId { get; set; }
        public int DWUpdatedId { get; set; }
        public bool DWIsDeleted { get; set; }
        public int DWPartitionKey { get; set; }
    
        public virtual CloudDim CloudDim { get; set; }
        public virtual DateDim DateDim { get; set; }
        public virtual HostDim HostDim { get; set; }
        public virtual HostGroupDim HostGroupDim { get; set; }
        public virtual PlanDim PlanDim { get; set; }
        public virtual SubscriptionDim SubscriptionDim { get; set; }
        public virtual TenantDim TenantDim { get; set; }
        public virtual UserRoleDim UserRoleDim { get; set; }
        public virtual VirtualMachineDim VirtualMachineDim { get; set; }
        public virtual VMMServerDim VMMServerDim { get; set; }
    }
}
