//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualNicDim
    {
        public VirtualNicDim()
        {
            this.VirtualMachineContainsVirtualNicFacts = new HashSet<VirtualMachineContainsVirtualNicFact>();
        }
    
        public int VirtualNicDimKey { get; set; }
        public System.Guid BaseManagedEntityId { get; set; }
        public string VMId { get; set; }
        public string MACAddress { get; set; }
        public Nullable<bool> VLANEnabled { get; set; }
        public string VLANId { get; set; }
        public string LogicalNetwork { get; set; }
        public string VMNetwork { get; set; }
        public string MACAddressType { get; set; }
        public string IPv6AddressType { get; set; }
        public string IPv4AddressType { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DWInsertedId { get; set; }
        public Nullable<int> DWUpdatedId { get; set; }
        public Nullable<bool> DWIsDeleted { get; set; }
    
        public virtual ICollection<VirtualMachineContainsVirtualNicFact> VirtualMachineContainsVirtualNicFacts { get; set; }
    }
}
