//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMHostDiskDim
    {
        public VMHostDiskDim()
        {
            this.HostHostsVMHostDiskFacts = new HashSet<HostHostsVMHostDiskFact>();
        }
    
        public int VMHostDiskDimKey { get; set; }
        public System.Guid BaseManagedEntityId { get; set; }
        public string ID { get; set; }
        public string Capacity { get; set; }
        public Nullable<bool> IsClustered { get; set; }
        public Nullable<bool> IsSanAttached { get; set; }
        public Nullable<bool> IsPassThroughCapable { get; set; }
        public string DiskID { get; set; }
        public string Location { get; set; }
        public string SMLunID { get; set; }
        public string AvailableCapacity { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DWInsertedId { get; set; }
        public Nullable<int> DWUpdatedId { get; set; }
        public Nullable<bool> DWIsDeleted { get; set; }
    
        public virtual ICollection<HostHostsVMHostDiskFact> HostHostsVMHostDiskFacts { get; set; }
    }
}
