//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMInventoryMonthlyFact
    {
        public long VMInventoryMonthlyFactKey { get; set; }
        public int HostDimKey { get; set; }
        public int VirtualMachineDimKey { get; set; }
        public int OperatingSystemDimKey { get; set; }
        public int ProcessorCategoryDimKey { get; set; }
        public int DateKey { get; set; }
        public string TargetType { get; set; }
        public string TargetName { get; set; }
        public string OperatingSystem { get; set; }
        public string ActivationStatus { get; set; }
        public Nullable<int> NumberOfProcessors { get; set; }
        public Nullable<int> MaxVMs { get; set; }
        public Nullable<System.DateTime> MaxVMTimeStamp { get; set; }
        public Nullable<int> LicensableUnits { get; set; }
        public int DWInsertedId { get; set; }
        public int DWUpdatedId { get; set; }
        public bool DWIsDeleted { get; set; }
    
        public virtual DateDim DateDim { get; set; }
        public virtual HostDim HostDim { get; set; }
        public virtual OperatingSystemDim OperatingSystemDim { get; set; }
        public virtual ProcessorCategoryDim ProcessorCategoryDim { get; set; }
        public virtual VirtualMachineDim VirtualMachineDim { get; set; }
    }
}
