//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLReporting.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMNetworkGatewayDim
    {
        public VMNetworkGatewayDim()
        {
            this.VMNetworkGatewayUsageMonthlyFacts = new HashSet<VMNetworkGatewayUsageMonthlyFact>();
            this.VMNetworkGatewayUsageDailyFacts = new HashSet<VMNetworkGatewayUsageDailyFact>();
            this.VMNetworkGatewayUsageDailyFactStagings = new HashSet<VMNetworkGatewayUsageDailyFactStaging>();
            this.VMNetworkGatewayUsageHourlyFacts = new HashSet<VMNetworkGatewayUsageHourlyFact>();
            this.VMNetworkGatewayUsageHourlyFactStagings = new HashSet<VMNetworkGatewayUsageHourlyFactStaging>();
        }
    
        public int VMNetworkGatewayDimKey { get; set; }
        public System.Guid BaseManagedEntityId { get; set; }
        public string VMNetworkId { get; set; }
        public string VMMServer { get; set; }
        public string GatewayName { get; set; }
        public Nullable<double> GatewayCapacityKbps { get; set; }
        public string GatewayDeviceId { get; set; }
        public Nullable<bool> MeteringSupported { get; set; }
        public string VMNetworkGatewayId { get; set; }
        public string IPv4Address { get; set; }
        public Nullable<double> VMNetworkCapacityInboundKbps { get; set; }
        public Nullable<double> VMNetworkCapacityOutboundKbps { get; set; }
        public string IPv6Address { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DWInsertedId { get; set; }
        public Nullable<int> DWUpdatedId { get; set; }
        public Nullable<bool> DWIsDeleted { get; set; }
    
        public virtual ICollection<VMNetworkGatewayUsageMonthlyFact> VMNetworkGatewayUsageMonthlyFacts { get; set; }
        public virtual ICollection<VMNetworkGatewayUsageDailyFact> VMNetworkGatewayUsageDailyFacts { get; set; }
        public virtual ICollection<VMNetworkGatewayUsageDailyFactStaging> VMNetworkGatewayUsageDailyFactStagings { get; set; }
        public virtual ICollection<VMNetworkGatewayUsageHourlyFact> VMNetworkGatewayUsageHourlyFacts { get; set; }
        public virtual ICollection<VMNetworkGatewayUsageHourlyFactStaging> VMNetworkGatewayUsageHourlyFactStagings { get; set; }
    }
}
